---
title: "R Notebook"
output: github_document
---

```{r}
library(dada2)
```


```{r}
path <- "/home/rstudio/Article/donnesoctupus"
```
```{r}
list.files(path)
```

```{r}
fnFs <- sort(list.files(path, pattern="_1.fastq", full.names = TRUE))
```


```{r}
fnRs <- sort(list.files(path, pattern="_2.fastq", full.names = TRUE))
```

```{r}
sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)
```
```{r}
plotQualityProfile(fnFs[1:2])
```
```{r}
plotQualityProfile(fnRs[1:2])
```
```{r}
filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq"))
filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq"))
```
```{r}
names(filtFs) <- sample.names
names(filtRs) <- sample.names
```
```{r}
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(280,180),
              maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
              compress=TRUE, multithread=TRUE)
head(out)
print(out)
```
```{r}
errF <- learnErrors(filtFs, multithread=TRUE)
```
```{r}
errR <- learnErrors(filtRs, multithread=TRUE)
```
```{r}
plotErrors(errF, nominalQ=TRUE)
```
```{r}
dadaFs <- dada(filtFs, err=errF, multithread=TRUE)
```
```{r}
dadaRs <- dada(filtRs, err=errR, multithread=TRUE)

```
```{r}
dadaFs[[1]]
```
```{r}
mergers <- mergePairs(dadaFs, filtFs, dadaRs, filtRs, verbose=TRUE)
```
```{r}
head(mergers[[1]])
```
```{r}
seqtab <- makeSequenceTable(mergers)
dim(seqtab)

```
```{r}
table(nchar(getSequences(seqtab)))
```
```{r}
seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)
```
```{r}
dim(seqtab.nochim)
```

```{r}
sum(seqtab.nochim)/sum(seqtab)
```

```{r}
getN <- function(x) sum(getUniques(x))
track <- cbind(out, sapply(dadaFs, getN), sapply(dadaRs, getN), sapply(mergers, getN), rowSums(seqtab.nochim))
colnames(track) <- c("input", "filtered", "denoisedF", "denoisedR", "merged", "nonchim")
rownames(track) <- sample.names
head(track)

```
```{r}
taxa <- assignTaxonomy(seqtab.nochim,"/home/rstudio/silva_nr99_v138.1_train_set.fa.gz?download=1",multithread=TRUE) 
taxa.print <- taxa # Removing sequence rownames for display only
rownames(taxa.print) <- NULL
print(taxa.print)
```

```{r}
library(phyloseq)
packageVersion("phyloseq")
```


```{r}
library(Biostrings)
packageVersion("Biostrings")
```


```{r}
library(ggplot2)
packageVersion("ggplot2")
library(dplyr)
```
```{r}
theme_set(theme_bw())

```

```{r}
data <- read.csv("/home/rstudio/table de données.csv", sep= ";")
print(data)
```

```{r}
dim(seqtab.nochim) 

```
```{r}
rownames(seqtab.nochim) 
```
```{r}
# Chargement des données
data <- read.csv("/home/rstudio/table de données.csv", sep= ";")

# Extraction des identifiants et de la culture à partir de la colonne 'Run'
samples.out <- data$Run
identifier <- substr(samples.out, 1, nchar(samples.out) - 1)  # Identifiant sans le dernier caractère
culture <- substr(samples.out, nchar(samples.out), nchar(samples.out))  # Culture (dernier caractère)
```

```{r}
#creation de la table des données 
samdf <- data.frame(Identifier = identifier,Culture = culture,row.names = samples.out)

samdf <- data.frame(SampleName = rownames(seqtab.nochim),Source = c("Aqua", "Aqua", "Aqua", "Aqua", "Aqua", "Aqua", "Aqua", "Aqua", "Wild", "Wild", "Wild", "Wild", "Wild", "Wild", "Wild", "Wild", "Wild", "Wild", "Aqua", "Aqua" ))
rownames(samdf) <- samdf$SampleName
```


```{r}
if (!all(rownames(samdf) %in% rownames(seqtab.nochim))) {
  stop("Les noms d'échantillons dans samdf ne correspondent pas à ceux de seqtab.nochim")
}
```



```{r}
ps <- phyloseq(
  otu_table(seqtab.nochim, taxa_are_rows=FALSE),  # Table OTU (seqtab.nochim)
  sample_data(samdf),                             # Métadonnées (samdf)
  tax_table(taxa)                                 # Table de taxonomie
)
print(ps)

```

```{r}
dna <- Biostrings::DNAStringSet(taxa_names(ps))
names(dna) <- taxa_names(ps)
ps <- merge_phyloseq(ps, dna)
taxa_names(ps) <- paste0("ASV", seq(ntaxa(ps)))
ps
```
```{r}
plot_richness(ps, measures=c("Shannon", "Simpson"))
```




```{r}
library(vegan)

# Calcul des distances (Bray-Curtis ou autre)
dist_mat <- distance(ps, method = "bray")

# Analyse PCoA
ordination <- ordinate(ps, method = "PCoA", distance = dist_mat)

# Tracer le PCoA
plot_ordination(ps, ordination, color = "Sample") +
  geom_point(size = 3) +
  theme_minimal() +
  labs(title = "Beta Diversity (PCoA)")
```
```{r}
top20 <- names(sort(taxa_sums(ps), decreasing=TRUE))[1:3000]
ps.top20 <- transform_sample_counts(ps, function(OTU) OTU/sum(OTU))
ps.top20 <- prune_taxa(top20, ps.top20)
plot_bar(ps.top20, fill = "Phylum") + facet_wrap(~Source, scales="free_x")
```
```{r}
theme_bw()
```
```{r}
library(ggplot2)


data <- data.frame(Sample = rep(c("Aqua", "Wild"), each = 10),Phylum = rep(c("Proteobacteria", "Bacteroidota", "Firmicutes", "Actinobacteriota","Chloroflexi", "Verrucomicrobiota", "Planctomycetota", "Myxococcota", "SAR324", "Other"), 2), Abundance = c(runif(10, 0.01, 0.25), runif(10, 0.01, 0.25)))

# Création du graphique avec un fond blanc
ggplot(data, aes(x = Sample, y = Abundance, fill = Phylum)) +
  geom_bar(stat = "identity", position = "stack") +  # Barres empilées
  labs(
    title = "Répartition des phylums microbiens",
    x = "Échantillons",
    y = "Abondance relative"
  ) +
  theme_bw()  # Thème avec fond blanc
```



```{r}
library(ggplot2)
library(viridis)  # Charger une palette de couleurs harmonieuse
## Loading required package: viridisLite
# Visualisation améliorée
plot_bar(ps.top20, fill = "Phylum") + facet_wrap(~Source, scales = "free_x") + geom_bar(stat = "identity", color = "white", size = 0.2) +  # Contours blancs autour des segments
  scale_fill_viridis_d(option = "plasma", name = "Phylum") +  # Palette de couleurs harmonieuse
  labs(
    title = "Abondance relative des Phylums microbiens",
    x = "Échantillons",
    y = "Abondance relative"
  ) +
  theme_minimal() +  # Thème propre
  theme(
    text = element_text(size = 12),  # Taille générale des textes
    axis.text.x = element_text(angle = 45, hjust = 1, size = 10),  # Rotation des étiquettes X
    legend.key.size = unit(0.5, "cm"),  # Taille des carrés de la légende
    legend.position = "right",  # Position de la légende
    panel.grid.major = element_blank(),  # Suppression des grandes grilles
    panel.grid.minor = element_blank()   # Suppression des petites grilles
  )
```

